### ISSUE TITLE
uncaughtException: Cannot parse config file: \'C:\\Users\\jdion\\Documents\\SOCIOBOARD\\socioboard-api\\notification\\config\\default.json\': SyntaxError: Unexpected token } 

### ISSUE THREAD

**Issue by JonathanDeBelg** [socioboard/Socioboard-4.0#143]
Hi,

I get the following error while running:
`socioboard-api\notification>nodemon app.js`
```
Error: Cannot parse config file: 'C:\Users\jdion\Documents\SOCIOBOARD\socioboard-api\notification\config\default.json': SyntaxError: Unexpected token } in JSON at position 1849
       at Config.util.parseFile (C:\Users\jdion\Documents\SOCIOBOARD\socioboard-api\notification\node_modules\config\lib\config.js:844:11)
       at C:\Users\jdion\Documents\SOCIOBOARD\socioboard-api\notification\node_modules\config\lib\config.js:600:28
       at Array.forEach (<anonymous>)
       at C:\Users\jdion\Documents\SOCIOBOARD\socioboard-api\notification\node_modules\config\lib\config.js:596:14
       at Array.forEach (<anonymous>)
       at Config.util.loadFileConfigs (C:\Users\jdion\Documents\SOCIOBOARD\socioboard-api\notification\node_modules\config\lib\config.js:595:13)
       at new Config (C:\Users\jdion\Documents\SOCIOBOARD\socioboard-api\notification\node_modules\config\lib\config.js:136:27)
       at Object.<anonymous> (C:\Users\jdion\Documents\SOCIOBOARD\socioboard-api\notification\node_modules\config\lib\config.js:1649:31)
       at Module._compile (internal/modules/cjs/loader.js:778:30)
       at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10),
  level: 'error',
  message:
   'uncaughtException: Cannot parse config file: \'C:\\Users\\jdion\\Documents\\SOCIOBOARD\\socioboard-api\\notification\\config\\default.json\': SyntaxError: Unexpected token } in JSON at position 1849\nError: Cannot parse config file: \'C:\\Users\\jdion\\Documents\\SOCIOBOARD\\socioboard-api\\notification\\config\\default.json\': SyntaxError: Unexpected token } in JSON at position 1849\n    at Config.util.parseFile (C:\\Users\\jdion\\Documents\\SOCIOBOARD\\socioboard-api\\notification\\node_modules\\config\\lib\\config.js:844:11)\n    at C:\\Users\\jdion\\Documents\\SOCIOBOARD\\socioboard-api\\notification\\node_modules\\config\\lib\\config.js:600:28\n    at Array.forEach (<anonymous>)\n    at C:\\Users\\jdion\\Documents\\SOCIOBOARD\\socioboard-api\\notification\\node_modules\\config\\lib\\config.js:596:14\n    at Array.forEach (<anonymous>)\n    at Config.util.loadFileConfigs (C:\\Users\\jdion\\Documents\\SOCIOBOARD\\socioboard-api\\notification\\node_modules\\config\\lib\\config.js:595:13)\n    at new Config (C:\\Users\\jdion\\Documents\\SOCIOBOARD\\socioboard-api\\notification\\node_modules\\config\\lib\\config.js:136:27)\n    at Object.<anonymous> (C:\\Users\\jdion\\Documents\\SOCIOBOARD\\socioboard-api\\notification\\node_modules\\config\\lib\\config.js:1649:31)\n    at Module._compile (internal/modules/cjs/loader.js:778:30)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)',
  stack:
   'Error: Cannot parse config file: \'C:\\Users\\jdion\\Documents\\SOCIOBOARD\\socioboard-api\\notification\\config\\default.json\': SyntaxError: Unexpected token } in JSON at position 1849\n    at Config.util.parseFile (C:\\Users\\jdion\\Documents\\SOCIOBOARD\\socioboard-api\\notification\\node_modules\\config\\lib\\config.js:844:11)\n    at C:\\Users\\jdion\\Documents\\SOCIOBOARD\\socioboard-api\\notification\\node_modules\\config\\lib\\config.js:600:28\n    at Array.forEach (<anonymous>)\n    at C:\\Users\\jdion\\Documents\\SOCIOBOARD\\socioboard-api\\notification\\node_modules\\config\\lib\\config.js:596:14\n    at Array.forEach (<anonymous>)\n    at Config.util.loadFileConfigs (C:\\Users\\jdion\\Documents\\SOCIOBOARD\\socioboard-api\\notification\\node_modules\\config\\lib\\config.js:595:13)\n    at new Config (C:\\Users\\jdion\\Documents\\SOCIOBOARD\\socioboard-api\\notification\\node_modules\\config\\lib\\config.js:136:27)\n    at Object.<anonymous> (C:\\Users\\jdion\\Documents\\SOCIOBOARD\\socioboard-api\\notification\\node_modules\\config\\lib\\config.js:1649:31)\n    at Module._compile (internal/modules/cjs/loader.js:778:30)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)',
  exception: true,
  date:
   'Mon Mar 09 2020 13:06:24 GMT+0100 (Central European Standard Time)',
```
Is there any fix for this issue?

**Comment by danieladi050** [comment]
how do you solve this @JonathanDeBelg

**Comment by JonathanDeBelg** [comment]
i think the config/development.json wasn't setup properly. Make sure the mongodb is set up.
