### ISSUE TITLE
error when starting microservice nodemon

### ISSUE THREAD

**Issue by danieladi050** [socioboard/Socioboard-4.0#153]
this is the log i get. can anyone help me ?

{ error:
   TypeError: Cannot read property 'use_env_variable' of undefined
       at Object.<anonymous> (C:\xampp\htdocs\socioboard\Socioboard-4.0-master\socioboard-api\library\sequelize-cli\models\index.js:12:12)
       at Module._compile (internal/modules/cjs/loader.js:776:30)
       at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
       at Module.load (internal/modules/cjs/loader.js:653:32)
       at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
       at Function.Module._load (internal/modules/cjs/loader.js:585:3)
       at Module.require (internal/modules/cjs/loader.js:690:17)
       at require (internal/modules/cjs/helpers.js:25:18)
       at Object.<anonymous> (C:\xampp\htdocs\socioboard\Socioboard-4.0-master\socioboard-api\user\startup\dbconnect.js:3:12)
       at Module._compile (internal/modules/cjs/loader.js:776:30)
       at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
       at Module.load (internal/modules/cjs/loader.js:653:32)
       at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
       at Function.Module._load (internal/modules/cjs/loader.js:585:3)
       at Module.require (internal/modules/cjs/loader.js:690:17)
       at require (internal/modules/cjs/helpers.js:25:18)
       at Object.<anonymous> (C:\xampp\htdocs\socioboard\Socioboard-4.0-master\socioboard-api\user\app.js:7:19)
       at Module._compile (internal/modules/cjs/loader.js:776:30)
       at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
       at Module.load (internal/modules/cjs/loader.js:653:32)
       at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
       at Function.Module._load (internal/modules/cjs/loader.js:585:3),
  level: 'error',
  message:
   'uncaughtException: Cannot read property \'use_env_variable\' of undefined\nTypeError: Cannot read property \'use_env_variable\' of undefined\n    at Object.<anonymous> (C:\\xampp\\htdocs\\socioboard\\Socioboard-4.0-master\\socioboard-api\\library\\sequelize-cli\\models\\index.js:12:12)\n    at Module._compile (internal/modules/cjs/loader.js:776:30)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)\n    at Module.load (internal/modules/cjs/loader.js:653:32)\n    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)\n    at Function.Module._load (internal/modules/cjs/loader.js:585:3)\n    at Module.require (internal/modules/cjs/loader.js:690:17)\n    at require (internal/modules/cjs/helpers.js:25:18)\n    at Object.<anonymous> (C:\\xampp\\htdocs\\socioboard\\Socioboard-4.0-master\\socioboard-api\\user\\startup\\dbconnect.js:3:12)\n    at Module._compile (internal/modules/cjs/loader.js:776:30)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)\n    at Module.load (internal/modules/cjs/loader.js:653:32)\n    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)\n    at Function.Module._load (internal/modules/cjs/loader.js:585:3)\n    at Module.require (internal/modules/cjs/loader.js:690:17)\n    at require (internal/modules/cjs/helpers.js:25:18)\n    at Object.<anonymous> (C:\\xampp\\htdocs\\socioboard\\Socioboard-4.0-master\\socioboard-api\\user\\app.js:7:19)\n    at Module._compile (internal/modules/cjs/loader.js:776:30)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)\n    at Module.load (internal/modules/cjs/loader.js:653:32)\n    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)\n    at Function.Module._load (internal/modules/cjs/loader.js:585:3)',
  stack:
   'TypeError: Cannot read property \'use_env_variable\' of undefined\n    at Object.<anonymous> (C:\\xampp\\htdocs\\socioboard\\Socioboard-4.0-master\\socioboard-api\\library\\sequelize-cli\\models\\index.js:12:12)\n    at Module._compile (internal/modules/cjs/loader.js:776:30)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)\n    at Module.load (internal/modules/cjs/loader.js:653:32)\n    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)\n    at Function.Module._load (internal/modules/cjs/loader.js:585:3)\n    at Module.require (internal/modules/cjs/loader.js:690:17)\n    at require (internal/modules/cjs/helpers.js:25:18)\n    at Object.<anonymous> (C:\\xampp\\htdocs\\socioboard\\Socioboard-4.0-master\\socioboard-api\\user\\startup\\dbconnect.js:3:12)\n    at Module._compile (internal/modules/cjs/loader.js:776:30)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)\n    at Module.load (internal/modules/cjs/loader.js:653:32)\n    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)\n    at Function.Module._load (internal/modules/cjs/loader.js:585:3)\n    at Module.require (internal/modules/cjs/loader.js:690:17)\n    at require (internal/modules/cjs/helpers.js:25:18)\n    at Object.<anonymous> (C:\\xampp\\htdocs\\socioboard\\Socioboard-4.0-master\\socioboard-api\\user\\app.js:7:19)\n    at Module._compile (internal/modules/cjs/loader.js:776:30)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)\n    at Module.load (internal/modules/cjs/loader.js:653:32)\n    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)\n    at Function.Module._load (internal/modules/cjs/loader.js:585:3)',
  exception: true,
  date: 'Fri Apr 03 2020 13:31:06 GMT+0700 (Indochina Time)',
  process:
   { pid: 4680,
     uid: null,
     gid: null,
     cwd:
      'C:\\xampp\\htdocs\\socioboard\\Socioboard-4.0-master\\socioboard-api\\user',
     execPath: 'C:\\Program Files\\nodejs\\node.exe',
     version: 'v10.16.0',
     argv:
      [ 'C:\\Program Files\\nodejs\\node.exe',
        'C:\\xampp\\htdocs\\socioboard\\Socioboard-4.0-master\\socioboard-api\\user\\app.js' ],
     memoryUsage:
      { rss: 70623232,
        heapTotal: 61009920,
        heapUsed: 37522656,
        external: 21059797 } },
  os: { loadavg: [ 0, 0, 0 ], uptime: 10090 },
  trace:
   [ { column: 12,
       file:
        'C:\\xampp\\htdocs\\socioboard\\Socioboard-4.0-master\\socioboard-api\\library\\sequelize-cli\\models\\index.js',
       function: null,
       line: 12,
       method: null,
       native: false },
     { column: 30,
       file: 'internal/modules/cjs/loader.js',
       function: 'Module._compile',
       line: 776,
       method: '_compile',
       native: false },
     { column: 10,
       file: 'internal/modules/cjs/loader.js',
       function: 'Module._extensions..js',
       line: 787,
       method: '.js',
       native: false },
     { column: 32,
       file: 'internal/modules/cjs/loader.js',
       function: 'Module.load',
       line: 653,
       method: 'load',
       native: false },
     { column: 12,
       file: 'internal/modules/cjs/loader.js',
       function: 'tryModuleLoad',
       line: 593,
       method: null,
       native: false },
     { column: 3,
       file: 'internal/modules/cjs/loader.js',
       function: 'Module._load',
       line: 585,
       method: '_load',
       native: false },
     { column: 17,
       file: 'internal/modules/cjs/loader.js',
       function: 'Module.require',
       line: 690,
       method: 'require',
       native: false },
     { column: 18,
       file: 'internal/modules/cjs/helpers.js',
       function: 'require',
       line: 25,
       method: null,
       native: false },
     { column: 12,
       file:
        'C:\\xampp\\htdocs\\socioboard\\Socioboard-4.0-master\\socioboard-api\\user\\startup\\dbconnect.js',
       function: null,
       line: 3,
       method: null,
       native: false },
     { column: 30,
       file: 'internal/modules/cjs/loader.js',
       function: 'Module._compile',
       line: 776,
       method: '_compile',
       native: false },
     { column: 10,
       file: 'internal/modules/cjs/loader.js',
       function: 'Module._extensions..js',
       line: 787,
       method: '.js',
       native: false },
     { column: 32,
       file: 'internal/modules/cjs/loader.js',
       function: 'Module.load',
       line: 653,
       method: 'load',
       native: false },
     { column: 12,
       file: 'internal/modules/cjs/loader.js',
       function: 'tryModuleLoad',
       line: 593,
       method: null,
       native: false },
     { column: 3,
       file: 'internal/modules/cjs/loader.js',
       function: 'Module._load',
       line: 585,
       method: '_load',
       native: false },
     { column: 17,
       file: 'internal/modules/cjs/loader.js',
       function: 'Module.require',
       line: 690,
       method: 'require',
       native: false },
     { column: 18,
       file: 'internal/modules/cjs/helpers.js',
       function: 'require',
       line: 25,
       method: null,
       native: false },
     { column: 19,
       file:
        'C:\\xampp\\htdocs\\socioboard\\Socioboard-4.0-master\\socioboard-api\\user\\app.js',
       function: null,
       line: 7,
       method: null,
       native: false },
     { column: 30,
       file: 'internal/modules/cjs/loader.js',
       function: 'Module._compile',
       line: 776,
       method: '_compile',
       native: false },
     { column: 10,
       file: 'internal/modules/cjs/loader.js',
       function: 'Module._extensions..js',
       line: 787,
       method: '.js',
       native: false },
     { column: 32,
       file: 'internal/modules/cjs/loader.js',
       function: 'Module.load',
       line: 653,
       method: 'load',
       native: false },
     { column: 12,
       file: 'internal/modules/cjs/loader.js',
       function: 'tryModuleLoad',
       line: 593,
       method: null,
       native: false },
     { column: 3,
       file: 'internal/modules/cjs/loader.js',
       function: 'Module._load',
       line: 585,
       method: '_load',
       native: false } ],
  timestamp: '2020-04-03T06:31:06.413Z' }
{ error:
   TypeError: Cannot read property 'use_env_variable' of undefined
       at Object.<anonymous> (C:\xampp\htdocs\socioboard\Socioboard-4.0-master\socioboard-api\library\sequelize-cli\models\index.js:12:12)
       at Module._compile (internal/modules/cjs/loader.js:776:30)
       at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
       at Module.load (internal/modules/cjs/loader.js:653:32)
       at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
       at Function.Module._load (internal/modules/cjs/loader.js:585:3)
       at Module.require (internal/modules/cjs/loader.js:690:17)
       at require (internal/modules/cjs/helpers.js:25:18)
       at Object.<anonymous> (C:\xampp\htdocs\socioboard\Socioboard-4.0-master\socioboard-api\user\startup\dbconnect.js:3:12)
       at Module._compile (internal/modules/cjs/loader.js:776:30)
       at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
       at Module.load (internal/modules/cjs/loader.js:653:32)
       at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
       at Function.Module._load (internal/modules/cjs/loader.js:585:3)
       at Module.require (internal/modules/cjs/loader.js:690:17)
       at require (internal/modules/cjs/helpers.js:25:18)
       at Object.<anonymous> (C:\xampp\htdocs\socioboard\Socioboard-4.0-master\socioboard-api\user\app.js:7:19)
       at Module._compile (internal/modules/cjs/loader.js:776:30)
       at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
       at Module.load (internal/modules/cjs/loader.js:653:32)
       at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
       at Function.Module._load (internal/modules/cjs/loader.js:585:3),
  level: 'error',
  message:
   'uncaughtException: Cannot read property \'use_env_variable\' of undefined\nTypeError: Cannot read property \'use_env_variable\' of undefined\n    at Object.<anonymous> (C:\\xampp\\htdocs\\socioboard\\Socioboard-4.0-master\\socioboard-api\\library\\sequelize-cli\\models\\index.js:12:12)\n    at Module._compile (internal/modules/cjs/loader.js:776:30)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)\n    at Module.load (internal/modules/cjs/loader.js:653:32)\n    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)\n    at Function.Module._load (internal/modules/cjs/loader.js:585:3)\n    at Module.require (internal/modules/cjs/loader.js:690:17)\n    at require (internal/modules/cjs/helpers.js:25:18)\n    at Object.<anonymous> (C:\\xampp\\htdocs\\socioboard\\Socioboard-4.0-master\\socioboard-api\\user\\startup\\dbconnect.js:3:12)\n    at Module._compile (internal/modules/cjs/loader.js:776:30)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)\n    at Module.load (internal/modules/cjs/loader.js:653:32)\n    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)\n    at Function.Module._load (internal/modules/cjs/loader.js:585:3)\n    at Module.require (internal/modules/cjs/loader.js:690:17)\n    at require (internal/modules/cjs/helpers.js:25:18)\n    at Object.<anonymous> (C:\\xampp\\htdocs\\socioboard\\Socioboard-4.0-master\\socioboard-api\\user\\app.js:7:19)\n    at Module._compile (internal/modules/cjs/loader.js:776:30)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)\n    at Module.load (internal/modules/cjs/loader.js:653:32)\n    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)\n    at Function.Module._load (internal/modules/cjs/loader.js:585:3)',
  stack:
   'TypeError: Cannot read property \'use_env_variable\' of undefined\n    at Object.<anonymous> (C:\\xampp\\htdocs\\socioboard\\Socioboard-4.0-master\\socioboard-api\\library\\sequelize-cli\\models\\index.js:12:12)\n    at Module._compile (internal/modules/cjs/loader.js:776:30)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)\n    at Module.load (internal/modules/cjs/loader.js:653:32)\n    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)\n    at Function.Module._load (internal/modules/cjs/loader.js:585:3)\n    at Module.require (internal/modules/cjs/loader.js:690:17)\n    at require (internal/modules/cjs/helpers.js:25:18)\n    at Object.<anonymous> (C:\\xampp\\htdocs\\socioboard\\Socioboard-4.0-master\\socioboard-api\\user\\startup\\dbconnect.js:3:12)\n    at Module._compile (internal/modules/cjs/loader.js:776:30)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)\n    at Module.load (internal/modules/cjs/loader.js:653:32)\n    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)\n    at Function.Module._load (internal/modules/cjs/loader.js:585:3)\n    at Module.require (internal/modules/cjs/loader.js:690:17)\n    at require (internal/modules/cjs/helpers.js:25:18)\n    at Object.<anonymous> (C:\\xampp\\htdocs\\socioboard\\Socioboard-4.0-master\\socioboard-api\\user\\app.js:7:19)\n    at Module._compile (internal/modules/cjs/loader.js:776:30)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)\n    at Module.load (internal/modules/cjs/loader.js:653:32)\n    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)\n    at Function.Module._load (internal/modules/cjs/loader.js:585:3)',
  exception: true,
  date: 'Fri Apr 03 2020 13:39:31 GMT+0700 (Indochina Time)',
  process:
   { pid: 15180,
     uid: null,
     gid: null,
     cwd:
      'C:\\xampp\\htdocs\\socioboard\\Socioboard-4.0-master\\socioboard-api\\user',
     execPath: 'C:\\Program Files\\nodejs\\node.exe',
     version: 'v10.16.0',
     argv:
      [ 'C:\\Program Files\\nodejs\\node.exe',
        'C:\\xampp\\htdocs\\socioboard\\Socioboard-4.0-master\\socioboard-api\\user\\app.js' ],
     memoryUsage:
      { rss: 71819264,
        heapTotal: 60485632,
        heapUsed: 38569272,
        external: 21099839 } },
  os: { loadavg: [ 0, 0, 0 ], uptime: 10595 },
  trace:
   [ { column: 12,
       file:
        'C:\\xampp\\htdocs\\socioboard\\Socioboard-4.0-master\\socioboard-api\\library\\sequelize-cli\\models\\index.js',
       function: null,
       line: 12,
       method: null,
       native: false },
     { column: 30,
       file: 'internal/modules/cjs/loader.js',
       function: 'Module._compile',
       line: 776,
       method: '_compile',
       native: false },
     { column: 10,
       file: 'internal/modules/cjs/loader.js',
       function: 'Module._extensions..js',
       line: 787,
       method: '.js',
       native: false },
     { column: 32,
       file: 'internal/modules/cjs/loader.js',
       function: 'Module.load',
       line: 653,
       method: 'load',
       native: false },
     { column: 12,
       file: 'internal/modules/cjs/loader.js',
       function: 'tryModuleLoad',
       line: 593,
       method: null,
       native: false },
     { column: 3,
       file: 'internal/modules/cjs/loader.js',
       function: 'Module._load',
       line: 585,
       method: '_load',
       native: false },
     { column: 17,
       file: 'internal/modules/cjs/loader.js',
       function: 'Module.require',
       line: 690,
       method: 'require',
       native: false },
     { column: 18,
       file: 'internal/modules/cjs/helpers.js',
       function: 'require',
       line: 25,
       method: null,
       native: false },
     { column: 12,
       file:
        'C:\\xampp\\htdocs\\socioboard\\Socioboard-4.0-master\\socioboard-api\\user\\startup\\dbconnect.js',
       function: null,
       line: 3,
       method: null,
       native: false },
     { column: 30,
       file: 'internal/modules/cjs/loader.js',
       function: 'Module._compile',
       line: 776,
       method: '_compile',
       native: false },
     { column: 10,
       file: 'internal/modules/cjs/loader.js',
       function: 'Module._extensions..js',
       line: 787,
       method: '.js',
       native: false },
     { column: 32,
       file: 'internal/modules/cjs/loader.js',
       function: 'Module.load',
       line: 653,
       method: 'load',
       native: false },
     { column: 12,
       file: 'internal/modules/cjs/loader.js',
       function: 'tryModuleLoad',
       line: 593,
       method: null,
       native: false },
     { column: 3,
       file: 'internal/modules/cjs/loader.js',
       function: 'Module._load',
       line: 585,
       method: '_load',
       native: false },
     { column: 17,
       file: 'internal/modules/cjs/loader.js',
       function: 'Module.require',
       line: 690,
       method: 'require',
       native: false },
     { column: 18,
       file: 'internal/modules/cjs/helpers.js',
       function: 'require',
       line: 25,
       method: null,
       native: false },
     { column: 19,
       file:
        'C:\\xampp\\htdocs\\socioboard\\Socioboard-4.0-master\\socioboard-api\\user\\app.js',
       function: null,
       line: 7,
       method: null,
       native: false },
     { column: 30,
       file: 'internal/modules/cjs/loader.js',
       function: 'Module._compile',
       line: 776,
       method: '_compile',
       native: false },
     { column: 10,
       file: 'internal/modules/cjs/loader.js',
       function: 'Module._extensions..js',
       line: 787,
       method: '.js',
       native: false },
     { column: 32,
       file: 'internal/modules/cjs/loader.js',
       function: 'Module.load',
       line: 653,
       method: 'load',
       native: false },
     { column: 12,
       file: 'internal/modules/cjs/loader.js',
       function: 'tryModuleLoad',
       line: 593,
       method: null,
       native: false },
     { column: 3,
       file: 'internal/modules/cjs/loader.js',
       function: 'Module._load',
       line: 585,
       method: '_load',
       native: false } ],
  timestamp: '2020-04-03T06:39:31.313Z' }
{ message: 'Cron setup intialized for monthly user stats...',
  level: 'info',
  timestamp: '2020-04-03T07:07:33.923Z' }
{ message: 'Mongo Database has been connected.',
  level: 'info',
  timestamp: '2020-04-03T07:07:36.064Z' }
{ message: 'Sequelize Database has been connected.',
  level: 'info',
  timestamp: '2020-04-03T07:07:36.163Z' }
{ message: 'Configuration property "payment.base_path" is not defined',
  level: 'error',
  timestamp: '2020-04-03T07:07:36.222Z' }
{ message: 'Cron setup intialized for monthly user stats...',
  level: 'info',
  timestamp: '2020-04-03T07:08:27.899Z' }
{ message: 'Mongo Database has been connected.',
  level: 'info',
  timestamp: '2020-04-03T07:08:30.017Z' }
{ message: 'Sequelize Database has been connected.',
  level: 'info',
  timestamp: '2020-04-03T07:08:30.115Z' }
{ message: 'Configuration property "payment.base_path" is not defined',
  level: 'error',
  timestamp: '2020-04-03T07:08:30.171Z' }
{ message: 'Cron setup intialized for monthly user stats...',
  level: 'info',
  timestamp: '2020-04-03T07:09:02.368Z' }
{ message: 'Mongo Database has been connected.',
  level: 'info',
  timestamp: '2020-04-03T07:09:04.507Z' }
{ message: 'Sequelize Database has been connected.',
  level: 'info',
  timestamp: '2020-04-03T07:09:04.628Z' }
{ message: 'Configuration property "payment.base_path" is not defined',
  level: 'error',
  timestamp: '2020-04-03T07:09:04.686Z' }
{ message: 'Cron setup intialized for monthly user stats...',
  level: 'info',
  timestamp: '2020-04-03T07:12:30.077Z' }
{ message: 'Mongo Database has been connected.',
  level: 'info',
  timestamp: '2020-04-03T07:12:32.192Z' }
{ message: 'Sequelize Database has been connected.',
  level: 'info',
  timestamp: '2020-04-03T07:12:32.301Z' }
{ message: 'Configuration property "payment.base_path" is not defined',
  level: 'error',
  timestamp: '2020-04-03T07:12:32.358Z' }

**Comment by danieladi050** [comment]
SORRY GUYS, SUCH A NOOB MISTAKE
